export type {
  PublicAvailability,
  PublicFact,
  PublicImage,
  PublicImageVariant,
  PublicImageVariants,
  PublicIncludedItems,
  PublicInspection,
  PublicMachineDetailV1,
  PublicMachinePassportV1,
  PublicMachineSummaryV1,
  PublicMoney,
  PublicRepairStatus,
  PublicSourceVerification,
  PublicTimelineEvent,
  PublicWarranty,
} from "@/lib/public-projection/contracts.ts";
